---
title: "Pierrette Lo's Resume"
author: Pierrette Lo
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "data/",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```



Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```


Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skills()
```

<br>

```{r, include=FALSE}
# if(params$pdf_mode){
#   cat("View this resume online with links at __")
# } else {
#   cat("[<i class='fas fa-download'></i> Download a PDF of this resume](https://github.com/lopierra/resume/raw/master/lo_resume.pdf)")
# }
```

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with R using the [**{pagedown}**](https://github.com/rstudio/pagedown) and [**{datadrivencv}**](https://github.com/nstrayer/datadrivencv) packages. 

Source code is available at [github.com/lopierra/resume](https://github.com/lopierra/resume).

Last updated on `r Sys.Date()`.



Main
================================================================================

Pierrette Lo, MS {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```


Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('experience')
```


Accomplishments and Awards {data-icon=award}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('awards_accomplishments')
```


Selected Publications and Presentations {data-icon=book}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('publications_aside')
```
:::

```{r}
CV %<>% print_section('publications')
```



```{r}
CV %<>% print_links()
```
